folio-org/mod-finance

README.md
https://issues.folio.org/browse/MODFUND-52
- Update readme as part of the verification
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> MODFUND-52 - Update Readme

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFUND-58
* Added `/_jsonSchema` interface to support json schemas loading
* Added permission `finance.all`
* Description minor fixes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> MODFUND-58

descriptors/ModuleDescriptor-template.json, ramls/budgets.raml, src/main/java/org/folio/rest/helper/BudgetsHelper.java, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/impl/BudgetsApi.java, src/main/java/org/folio/rest/impl/FundsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/budgets/budgets.json
[MODFIN-61](https://issues.folio.org/browse/MODFIN-61) Define and Implement Budget API
- RAML is defined
- Module descriptor is updated with endpoints/permissions definitions
- APIs are implemented to proxy back to storage module APIs
- Unit tests are updated
=> MODFIN-61 Define and Implement Budget API

descriptors/ModuleDescriptor-template.json, ramls/fiscal-years.raml, src/main/java/org/folio/rest/helper/FiscalYearsHelper.java, src/main/java/org/folio/rest/impl/FiscalYearsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/fiscal-years/fiscal_years.json
https://issues.folio.org/browse/MODFIN-69
* Implement the fiscal year APIs described on the [wiki](https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-APIs.6)
* Implementing fiscal year API …
=> MODFIN-69 Implement basic Fiscal Year API

src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/fiscal-years/fiscal_years.json, src/test/resources/mockdata/ledgers/ledgers.json
[MODFISTO-49](https://issues.folio.org/browse/MODFISTO-49) - Ledger/LedgerFY updates: Schema changes
- Following [PR#189](https://github.com/folio-org/acq-models/pull/189), sample data and unit tests need to be updated …
=> MODFISTO-49 - Ledger/LedgerFY updates: Schema changes

README.md
So people know where to report issues.
=> FOLIO-673 Link to issue tracker

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/util/HelperUtils.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/FundsTest.java, src/test/resources/mockdata/ledgers/ledgers.json
[MODFIN-78](https://issues.folio.org/browse/MODFIN-78) update the fund GET APIs to use the new composite_fund schema
- GET /finance/funds/{id} returns CompositeFund containing the fund and the list of group ids related to fund for the current year.
- to get current FY see https://github.com/folio-org/mod-finance/pull/12 description
Ideally all of the PRs …
=> MODFIN-78 Fund API updates: GET by id/GET by query

descriptors/ModuleDescriptor-template.json, ramls/groups.raml, ramls/ledgers.raml, src/main/java/org/folio/rest/helper/GroupsHelper.java, src/main/java/org/folio/rest/impl/GroupsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/groups/groups.json
[MODFIN-68](https://issues.folio.org/browse/MODFIN-68) implement the Groups API in the business logic layer
- adding raml for groups API
- implementing groups API
- updating moduleDescriptor to add groups interface
- updating unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> MODFIN-68 Implement Groups API

src/test/resources/mockdata/group-fund-fiscal-years/group_fund_fiscal_years.json
https://issues.folio.org/browse/MODFIN-81
* pointed acq-models submodule to the latest master  …
=> MODFIN-81 Create awaiting_payment schema

descriptors/ModuleDescriptor-template.json, ramls/rtypes/post-json-201.raml, ramls/rtypes/post-json-204.raml, ramls/transaction.raml, src/main/java/org/folio/rest/helper/TransactionsHelper.java, src/main/java/org/folio/rest/impl/LedgersApi.java, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/transactions/allocations.json, src/test/resources/mockdata/transactions/encumbrances.json, src/test/resources/mockdata/transactions/transactions.json, src/test/resources/mockdata/transactions/transfers.json
https://issues.folio.org/browse/MODFIN-70
- Create API for allocations, transfers, encumbrances, transaction
- Add unit tests
- Add permissions in module descriptor
- Changes for acq-model, add examples https://github.com/folio-org/acq-models/pull/198
- Extra: Removed unused import from Ledgers API
Ideally all of the PRs involved in breaking changes …
=> MODFIN-70: Create transaction APIs - Allocations, Transfers, Encumbrances

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/transaction-summary.raml, ramls/transaction.raml, src/main/java/org/folio/rest/helper/TransactionSummariesHelper.java, src/main/java/org/folio/rest/impl/TransactionSummariesAPI.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/transaction-summaries/order_transaction_summary.json, src/test/resources/mockdata/transactions/allocations.json, src/test/resources/mockdata/transactions/encumbrances.json, src/test/resources/mockdata/transactions/transfers.json
https://issues.folio.org/browse/MODFIN-88
- created new API and unit tests
Additional
- corrected few  mockdata files
- renamed few methods to increase readibility
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> MODFIN-88- order-transaction-summaries

src/main/java/org/folio/rest/impl/FiscalYearsApi.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java
https://issues.folio.org/browse/MODFIN-94
- During POST and PUT, always calculate `series`
- Add unit tests
Extra: 
- Fix `ArrayIndexOutOfBound` console error 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> MODFIN-94: Add series field while creating a FiscalYear

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/rest/helper/FiscalYearsHelper.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/HelperUtils.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java, src/test/java/org/folio/rest/impl/FundsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/configurationEntries/EmptyConfig.json, src/test/resources/mockdata/configurationEntries/config_localeSEK.json, src/test/resources/mockdata/configurationEntries/invalid_config.json
https://issues.folio.org/browse/MODFIN-65
- fetch config from mod-configuration
- if the config is empty use the default values, values fetched from ui-tenant-settings. 
The locale entry is created only when the settings are edited
- Also set the RMB to latest version
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
=> MODFIN-65- Adding currency during FY creation

descriptors/ModuleDescriptor-template.json, ramls/ledgers.raml, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/impl/LedgersApi.java, src/main/java/org/folio/rest/impl/TransactionSummariesAPI.java, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/CurrentFiscalYearTest.java, src/test/java/org/folio/rest/impl/FundsTest.java
[/MODFIN-93](https://issues.folio.org/browse/MODFIN-93) Create an API to fetch the current FY for a ledger
Fetching the currentFY for a given ledger record. could be a simple GET /finance/ledgers/{id}/current-fiscal-year.
GET /finance/ledgers/{id}/current-fiscal-year
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
=> MODFIN-93 - Create an API to fetch the current FY for a ledger

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/FundsHelper.java, src/test/java/org/folio/rest/impl/FundsTest.java
[MODFIN-99](https://issues.folio.org/browse/MODFIN-99) - Update groupFundFiscalYear when fund is updated
To support UI flow of showing related funds we need to update groupFundFiscalYear table accordingly (set budgetId there).
Adding budgetId in the GroupFundFiscalYear during funds updating.
Ideally all of the PRs involved in breaking changes would be …
=> MODFIN-99 - Update groupFundFiscalYear when fund is updated

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/helper/GroupFundFiscalYearHelper.java, src/main/java/org/folio/rest/impl/BudgetsApi.java, src/test/java/org/folio/rest/util/MockServer.java
https://issues.folio.org/browse/MODFIN-97
* Updating groupFundFiscalYear table upon creation of budget
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> MODFIN-97 Update groupFundFiscalYear when budget is created

src/main/java/org/folio/rest/helper/AbstractHelper.java
https://issues.folio.org/browse/MODFIN-101
*  set default headers …
=> MODFIN-101 set default headers

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/ledgers.raml, src/main/java/org/folio/rest/helper/LedgersHelper.java, src/main/java/org/folio/rest/impl/LedgersApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/LedgerSummaryTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/resources/mockdata/ledger-fiscal-year/ledger-fiscal-years.json, src/test/resources/mockdata/ledgers/ledgers.json
[MODFIN-98](https://issues.folio.org/browse/MODFIN-98) 
- updating ledger.raml to add optional fiscalYear parameter
- getеting ledger with summary from ledgerFY record if fiscalYear param exist
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
=> MODFIN-98 Ledger not displaying correct allocated total

pom.xml, src/main/java/org/folio/rest/helper/AbstractHelper.java, src/main/java/org/folio/rest/helper/BudgetsHelper.java, src/main/java/org/folio/rest/helper/FiscalYearsHelper.java, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/helper/GroupFundFiscalYearHelper.java, src/main/java/org/folio/rest/helper/GroupsHelper.java, src/main/java/org/folio/rest/helper/LedgersHelper.java, src/main/java/org/folio/rest/helper/TransactionsHelper.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/HelperUtils.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/budgets/budgets.json, src/test/resources/mockdata/fiscal-years/fiscal_years.json
https://issues.folio.org/browse/MODFIN-105
- Create allocation transaction after budget is created if allocated > 0
- even if the transaction creation fails, budget is created 
Additional Changes
- moved few FY unit tests to it's own class
- moved common method from helperUtils to Abstract class 
Ideally all of the PRs involved in breaking changes would …
=> MODFIN-105: creating allocation transaction during budget creation

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
[MODFIN-104](https://issues.folio.org/browse/MODFIN-104) Create bugfix release for mod-finance
- updated news.md
- increased finance.group-fiscal-year-summaries, finance.ledgers minor versions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MODFIN-104 - Release 1.0.1

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://issues.folio.org/browse/MODFIN-107: finance storage has sample data with new fields added
- point to latest ledger interface
- increment the ledger interface version …
=> MODFIN-107: Release 1.1.0

descriptors/ModuleDescriptor-template.json, ramls/ledgers.raml, src/main/java/org/folio/rest/helper/LedgersHelper.java, src/main/java/org/folio/rest/impl/LedgersApi.java, src/main/java/org/folio/rest/util/HelperUtils.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java
[MODFIN-106](https://issues.folio.org/browse/MODFIN-106) - Add fiscalYear query arg to GET /finance/ledgers API
The basic implementation of GET /finance/ledgers exists, but needs to be augmented to support the ability to get the summary values (available, unavailable, allocated) for the ledgers.
A fiscalYear query parameter can be specified when calling GET /finance/ledgers and the results will be populated with appropriate summary data
- Do JIRAs exist to update the impacted …
=> MODFIN-106 - Add fiscalYear query arg to GET /finance/ledgers API

ramls/ledgers.raml, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/util/HelperUtils.java
[MODFIN-108](https://issues.folio.org/browse/MODFIN-108) - Get current fiscal year should include the start and end days in the period …
=> MODFIN-108 - Get current fiscal year should include the start and end days in the period

descriptors/ModuleDescriptor-template.json
- Add missing permission
- Gives the following error on creating a budget if `allocated` is >0
```
"errors" : [ {
"message" : "Failed to create allocation transaction for a budget",
"code" : "failedAllocationTransaction",
"parameters" : [ ]
} ]
```
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> Missing permission POST transaction in POST budget

src/main/java/org/folio/rest/helper/TransactionSummariesHelper.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/util/TestEntities.java
Follow-up for https://issues.folio.org/browse/MODFIN-71
Throw an exception only if count < 0
- Update `validateTransactionCount` to throw an exception only if summary count is less than 0
- This should be allowed:
```
{
"id": "5c156d82-96c3-4d9a-98e9-0c9a4184cf2c",
"numEncumbrances": 0,
"numPaymentsCredits": 2
}
```
Ideally all of the PRs involved in …
=> Follow-up of MODFIN-71: Invalid transaction summary count only if count is less than 0

pom.xml, ramls/release-encumbrance.raml, src/main/java/org/folio/rest/helper/BudgetsHelper.java, src/main/java/org/folio/rest/impl/BudgetsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/BudgetsTest.java
https://issues.folio.org/browse/MODFIN-86
* Added allowable amount restrictions
* added unit test
* code refactoring
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MODFIN-86 Restrict adjustment of budget's

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/BudgetsHelper.java
https://issues.folio.org/browse/MODFIN-86
* Calculation fixed according to [wiki](https://wiki.folio.org/pages/viewpage.action?spaceKey=FOLIJET&title=Finance+Data+Model#FinanceDataModel-TransactionRestrictions) …
=> MODFIN-86 calculation fixed

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/TransactionsHelper.java, src/test/java/org/folio/rest/impl/ApiTestBase.java, src/test/java/org/folio/rest/impl/EncumbrancesTest.java, src/test/resources/mockdata/awating_payment/awaiting_payment_1.json
[MODFIN-113](https://issues.folio.org/browse/MODFIN-113) Update the awaitingPayment API to set transaction.sourceInvoiceId and transaction.sourceInvoiceLineId on the encumbrance. …
=> MODFIN-113 Add invoiceId and invoiceLineId to the awaitingPayment schema	

NEWS.md, pom.xml, ramls/awaiting-payment.raml, ramls/ledgers.raml, ramls/transaction-summary.raml, ramls/transaction.raml
https://issues.folio.org/browse/MODFIN-62
* upodated raml versions
* updated release notes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> MODFIN-62 release 2.0.0

src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/HelperUtils.java, src/test/java/org/folio/rest/impl/BudgetsTest.java, src/test/java/org/folio/rest/util/MockServer.java
[MODFIN-117](https://issues.folio.org/browse/MODFIN-117)
Able to return user friendly JSON error, when Budget can't be deleted
- If received message from storage contains error code, which in the ErrorCodes enum - than build error with appropriate ErrorCodes instance, else use message from storage layer
Ideally all of the PRs involved in breaking changes …
=> [MODFIN-117] - Return meaningful error message upon failed budget deletion

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://issues.folio.org/browse/MODFIN-118
Bugfix release
=> Tmp bugfix 2.0.1

descriptors/ModuleDescriptor-template.json, ramls/exchange-rate.raml, src/main/java/org/folio/rest/helper/AbstractHelper.java, src/main/java/org/folio/rest/helper/ExchangeRateHelper.java, src/main/java/org/folio/rest/impl/ExchangeRateApi.java, src/main/resources/javamoney.properties, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/ExchangeRateTest.java
[MODFIN-111](https://issues.folio.org/browse/MODFIN-111) - Exchange rate API
Create an API for obtaining an exchangeRate between two currencies.
* Leverage the JavaMoney API
* Created schema and example
* The API is defined and implemented (RAML/ModDescr/Code)
* Unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in …
=> MODFIN-111 - Exchange rate API

.gitignore, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/ExchangeRateHelper.java, src/main/resources/javamoney.properties
https://issues.folio.org/browse/MODFIN-122
* fixed ExchangeRate config
* increased container memory up to 448MB
by mistake all exchange rates are retrived starting from year 1999. I have prepared test which make a call to the exchange endpoint every 3 seconds.
So the picture of memory utilization changed:
left - before
right - after the fix
Ideally all …
=> MODFIN-122 fixed exchange rate memory issue

descriptors/ModuleDescriptor-template.json, src/test/resources/mockdata/transactions/allocations.json, src/test/resources/mockdata/transactions/credits.json, src/test/resources/mockdata/transactions/encumbrances.json, src/test/resources/mockdata/transactions/payments.json, src/test/resources/mockdata/transactions/transactions.json, src/test/resources/mockdata/transactions/transfers.json
[MODFISTO-85](https://issues.folio.org/browse/MODFISTO-85) - Update the transaction 'source' enum
Update `acq-models` submodule after schema changes
`acq-models` submodule updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> MODFISTO-85 - Update the transaction 'source' enum

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-129
* added missed permission
While it's helpful …
=> MODFIN-129 added missed permission

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/rtypes/post-put-json.raml, ramls/transaction-summary.raml, src/main/java/org/folio/rest/helper/TransactionSummariesHelper.java, src/main/java/org/folio/rest/impl/TransactionSummariesAPI.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java
https://issues.folio.org/browse/MODFISTO-109
add PUT order transaction summary method
* https://issues.folio.org/browse/MODFISTO-109 …
=> MODFISTO-109 add PUT order transaction summary method

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
[MODFIN-132](https://issues.folio.org/browse/MODFIN-132)
- updated news
- updated provided and requires versions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> MODFIN-132 Release 3.0.0

descriptors/ModuleDescriptor-template.json, ramls/transaction.raml, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/test/java/org/folio/rest/impl/TransactionTest.java
[MODFIN-134](https://issues.folio.org/browse/MODFIN-134) - Create PUT /finance/encumbrance/id API
PUT /finance/encumbrance/id API need to be created to update encumbrance
* PUT /finance/encumbrance/id API created
* unit tests updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> MODFIN-134 - Create PUT /finance/encumbrance/id API

ramls/expense-classes.raml, src/main/java/org/folio/services/BudgetExpenseClassTotalsService.java, src/test/java/org/folio/rest/impl/BudgetsApiTest.java, src/test/java/org/folio/services/BudgetExpenseClassTotalsServiceTest.java
Update code after reverting expense class status schema folio-org/acq-models#262
While …
=> MODFIN-136 Define and implement GET /finance/budgets/id/expense-classes API

descriptors/ModuleDescriptor-template.json, ramls/funds.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/FundsApi.java, src/main/java/org/folio/services/FundDetailsService.java, src/test/java/org/folio/services/FundDetailsServiceTest.java
[Expense classes for fund](https://issues.folio.org/browse/MODFIN-141)
Added parameter in URL which responsible for filtering by expense class status
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> Modfin 141 hot fix

src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/test/java/org/folio/rest/impl/EncumbrancesTest.java
https://issues.folio.org/browse/MODFIN-112 Fix error codes …
=> MODFIN-112 Shouldn't allow negative payments or credits

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/BudgetsHelper.java, src/test/java/org/folio/rest/impl/BudgetsTest.java
[MODFIN-147](https://issues.folio.org/browse/MODFIN-147) 
- ignore budget's totals upon update …
=> MODFIN-147 Budget allocation calculation out of sync with transaction log

NEWS.md
[MODFIN-149](https://issues.folio.org/browse/MODFIN-149) …
=> MODFIN-149 MODFIN (mod-finance) Hotfix release

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/transaction.raml, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java
[MODFIN-145](https://issues.folio.org/browse/MODFIN-145)
- Implement PUT /finance/pending-payments proxy API to /finance-storage/transactions/id
- Update tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> [MODFIN-145] Define and implement PUT /finance/pending-payments/id API

descriptors/ModuleDescriptor-template.json, ramls/transaction-summary.raml, src/main/java/org/folio/rest/helper/TransactionSummariesHelper.java, src/main/java/org/folio/rest/impl/TransactionSummariesAPI.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/MockServer.java
https://issues.folio.org/browse/MODFIN-153
* Implemented PUT /finance/invoice-transaction-summary …
=> MODFIN-153 Implemented PUT /finance/invoice-transaction-summary

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/FundDetailsService.java, src/test/java/org/folio/services/FundDetailsServiceTest.java
https://github.com/folio-org/mod-finance-storage/pull/150 increase finance-storage.ledgers interface dependency version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> MODFISTO-122 Remove ledgerFY totals calculation logic

Dockerfile, Jenkinsfile, pom.xml
https://issues.folio.org/browse/MODFIN-142
* update RMB v31.1.1 …
=> MODFIN-142 RMB v31.1.1

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
[MODFIN-140](https://issues.folio.org/browse/MODFIN-140) …
=> MODFIN-140 - Release - 4.0.0

pom.xml
[MODFIN-163](https://issues.folio.org/browse/MODFIN-163)
No logging in honeysuckle version
- update pom file to fix logging
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
=> [MODFIN-163] No logging in honeysuckle version

src/main/java/org/folio/rest/util/MoneyUtils.java, src/main/java/org/folio/services/GroupExpenseClassTotalsService.java, src/main/java/org/folio/services/budget/BudgetExpenseClassTotalsService.java, src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/test/java/org/folio/services/CommonTransactionServiceTest.java, src/test/java/org/folio/services/GroupExpenseClassTotalsServiceTest.java
[MODFIN-159](https://issues.folio.org/browse/MODFIN-159) …
=> MODFIN-159 Update logic for calculating group expense classes totals

src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/test/java/org/folio/services/GroupExpenseClassTotalsServiceTest.java
[MODFIN-165](https://issues.folio.org/browse/MODFIN-165)
- fixed retrieve transactions query …
=> MODFIN-165 Some transactions are not considered when calculating group expense-class-totals

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-164
* updated release notes
While it's helpful …
=> MODFIN-164 release 4.0.1

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/ledger_rollover.raml, src/main/java/org/folio/config/RestClientsConfiguration.java, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/LedgerRolloverApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/LedgerRolloverService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/LedgerRolloverApiTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/java/org/folio/services/LedgerRolloverServiceTest.java, src/test/resources/mockdata/ledger-rollovers/ledger-rollovers.json
[MODFIN-157](https://issues.folio.org/browse/MODFIN-157)
Define business API for the ledger fiscal year rollover
- Define proxy api for get, get by id and post method
- Add tests …
=> MODFIN-157 Define business API for the ledger fiscal year rollover

descriptors/ModuleDescriptor-template.json, ramls/ledger_rollover_progress.raml, src/main/java/org/folio/config/RestClientsConfiguration.java, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/LedgerRolloverProgressApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/LedgerRolloverProgressService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/LedgerRolloverProgressApiTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/java/org/folio/services/LedgerRolloverProgressServiceTest.java
[MODFIN-158](https://issues.folio.org/browse/MODFIN-158)
Define business API for retrieving rollover status/progress
- Define GET, GET BY ID, PUT, POST business proxy api for ledger rollover progress
- Add tests …
=> MODFIN-158 Define business API for retrieving rollover status/progress

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/LedgerTotalsService.java, src/test/java/org/folio/services/LedgerTotalsServiceTest.java
[MODFIN-168](https://issues.folio.org/browse/MODFIN-168)
Updated logic for the services org.folio.services.LedgerTotalsService to sum new Budgets fields
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> MODFIN-168 Update logic with financial detail in the Ledger summary to improve the users ability to manage financial activity

src/test/java/org/folio/services/LedgerDetailsServiceTest.java
https://issues.folio.org/browse/MODFIN-173
build failed https://jenkins-aws.indexdata.com/job/folio-org/job/mod-finance/job/master/122/execution/node/53/log/
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> MODFIN-173 Update /finance/group-fiscal-year-summaries API to include more summary information

src/main/java/org/folio/services/budget/BudgetService.java, src/test/java/org/folio/services/budget/BudgetServiceTest.java
https://issues.folio.org/browse/MODFIN-175 …
=> Modfin 175

src/main/java/org/folio/services/LedgerRolloverErrorsService.java
"Unsupported Media Type" error when request endpoint with accept header "application/json, text/plain"
* fixed Accept header check  …
=> MODFINANCE-162 fixed Accept header check

descriptors/ModuleDescriptor-template.json
Fix https://jenkins-aws.indexdata.com/job/FOLIO_Reference_Builds/job/folio-testing-backend/796/consoleFull
move `acquisitions-units-storage.*` interfaces from `requires` section to `optional`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> Fix failed build

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-183
Fix permission name …
=> [MODFIN-183] - Fix permission

descriptors/ModuleDescriptor-template.json
=> [MODFIN-188] - Adding a lost permission

PERSONAL_DATA_DISCLOSURE.md, PERSONAL_DATA_DISCLOSURE.md.txt
=> [MODFIN-172] -  Add personal data disclosure form

NEWS.md, pom.xml
Release 4.1.0
While it's helpful for reviewers to help identify potential problems, …
=> [MODFIN-169] - Release 4.1.0

NEWS.md, pom.xml
[MODFISTO-232](https://issues.folio.org/browse/MODFISTO-232)
Unable to complete fiscal year rollover …
=> Tmp release 4.1.1

NEWS.md, src/main/java/org/folio/services/transactions/BaseTransactionService.java
=> Tmp release 4.1.2

NEWS.md
=> MODFIN-198 Sync news.md

pom.xml, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/services/fund/FundDetailsService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/util/HelperUtilsTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/services/ledger/LedgerDetailsServiceTest.java, src/test/java/org/folio/services/ledger/LedgerRolloverErrorsServiceTest.java, src/test/java/org/folio/services/ledger/LedgerRolloverProgressServiceTest.java, src/test/java/org/folio/services/ledger/LedgerRolloverServiceTest.java
https://issues.folio.org/browse/MODFIN-191
* updated rmb 33.0.0
* completely migrated to junit5 …
=> MODFIN-191 update rmb 33.0.0

NEWS.md, pom.xml
* https://issues.folio.org/browse/MODFIN-190
* updated release notes
While it's helpful …
=> MODFIN-190 Release 4.2.0

src/main/java/org/folio/rest/impl/FiscalYearsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java, src/test/java/org/folio/rest/util/TestConstants.java
https://issues.folio.org/browse/MODFIN-201
Created FISCAL_YEAR_INVALID_PERIOD code in the ErrorCodes class.
Validating period start and end dates of fiscal year in the API layer. …
=> MODFIN-201 - Validate period when creating/updating fiscal year

descriptors/ModuleDescriptor-template.json, ramls/transaction.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/transactions/AllocationService.java, src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/main/java/org/folio/services/transactions/CreditService.java, src/main/java/org/folio/services/transactions/EncumbranceService.java, src/main/java/org/folio/services/transactions/PaymentService.java, src/main/java/org/folio/services/transactions/PendingPaymentService.java, src/main/java/org/folio/services/transactions/TransactionManagingService.java, src/main/java/org/folio/services/transactions/TransactionService.java, src/main/java/org/folio/services/transactions/TransactionStrategyFactory.java, src/main/java/org/folio/services/transactions/TransferService.java, src/test/java/org/folio/rest/impl/TransactionApiTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/rest/util/TestEntities.java
[MODFIN-207](https://issues.folio.org/browse/MODFIN-207) - Create business API for removing Encumbrance transactions
- Added `DELETE /finance/encumbrances/{id}`
(the path could have been `/finance/transactions/{id}`, but with `/encumbrances/` it is clear that this can only be used for encumbrances)
- Validation: encumbrances cannot have `amountExpended > 0`, and cannot have a related `awaitingPayment` transaction (case of an approved invoice)
- Unit tests check for a successful delete and for the 2 cases that are not allowed …
=> [MODFIN-207] Added API to remove encumbrance transactions

descriptors/ModuleDescriptor-template.json
[MODFISTO-244](https://issues.folio.org/browse/MODFISTO-244) - Add validation for special character to Fund Code and Expense class code and prepare migration script
- Updated model with new restrictions for fund and expense class codes
- Incremented API version for expense class API
Ideally all of the PRs involved in breaking changes would be merged in …
=> [MODFISTO-244] Fund and expense class code restrictions

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-211
* updated release notes
While it's helpful …
=> MODFIN-211 release notes 4.3.0 (Kiwi)

pom.xml, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/resources/javamoney.properties
https://issues.folio.org/browse/MODFIN-213
* excluded IMF and ECB_Historical from currency rates providers
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> MODFIN - 213 Exchange rates update completes with error

src/main/java/org/folio/rest/helper/FundsHelper.java
Fix DELETE /fund randomly fails
While it's helpful for reviewers to help identify …
=> MODFIN-215 Fixed DELETE /fund randomly fails

src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/transactions/EncumbranceService.java, src/test/java/org/folio/rest/impl/TransactionApiTest.java
https://issues.folio.org/browse/MODFIN-217
* Do not release transaction in scope of DELETE transaction API
* Deletion of unreleased transactions blocked
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> MODFIN-217  Incorrect usage of all-or-nothing mechanism while removing transactions

pom.xml
https://issues.folio.org/browse/MODFIN-220 …
=> MODFIN-220. Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-223 …
=> MODFIN-223 Kiwi Hotfix 4.3.2

pom.xml
https://issues.folio.org/browse/MODFIN-221 …
=> MODFIN-221. Juniper R2 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-222 …
=> MODFIN-222. Juniper R2 2021 HF #5 module release

src/main/java/org/folio/services/budget/BudgetService.java, src/test/java/org/folio/services/budget/BudgetServiceTest.java
Fix add expense class to budget
While it's helpful for reviewers to help identify …
=> [MODFIN-224] - Fix add expense class to budget

pom.xml, src/main/java/org/folio/services/budget/BudgetService.java
* [MODFIN-224] - Fix add expense class to budget
* [MODFIN-224] - Test fix
* [MODFIN-224] - Test fix
(cherry picked from commit 607e16a3f6c11f8ea858111b8edf492b7e7b9b35) …
=> [MODFIN-224] - Fix add expense class to budget (#150)

NEWS.md, pom.xml
Release version 4.3.3
While it's helpful for reviewers to help identify potential …
=> [MODFIN-226] - Update NEWS

descriptors/ModuleDescriptor-template.json, ramls/transaction.raml, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/transactions/CreditService.java, src/main/java/org/folio/services/transactions/PaymentService.java, src/test/java/org/folio/rest/impl/TransactionApiTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/transactions/transactions.json
[MODFIN-230](https://issues.folio.org/browse/MODFIN-230) - Allow PUT for payments/credits to cancel invoices
- Updated descriptor and RAML.
- Added PUT implementation for payments and credits, with a validation to make sure invoiceCancelled is true and nothing else is changed.
- Added unit tests.
Integration testing can be done with [MODINVOICE-270](https://issues.folio.org/browse/MODINVOICE-270).
- Are the JIRAs under active …
=> [MODFIN-230] PUT for payments and credits

descriptors/ModuleDescriptor-template.json
Add finance-storage.transactions.item.get permission …
=> [MODFIN-236] - Added permissions

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-235
* update release notes …
=> MODFIN-235 Lotus 2022 R1 module release 4.4.0

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/rest/helper/ExchangeRateHelper.java, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/resources/javamoney.properties
https://issues.folio.org/browse/MODFIN-237
* fixed money api configuration
While it's …
=> MODFIN-237 fixed money api configuration

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/util/HelperUtils.java
[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
- Updated schemas
- Updated affected API versions
- Report a 409 if a 409 is returned from storage.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> [MODFISTO-303] update for optimistic locking

NEWS.md, pom.xml
https://issues.folio.org/browse/MODFIN-252
Add release notes 4.5.0 for Morning Glory R2 release
=> [MODFIN-252] Morning Glory R2 2022 release

descriptors/ModuleDescriptor-template.json
=> [MODFIN-263] - A user with certain permission can not create planned budget

NEWS.md, descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-266
=> [MODFIN-266] Release 2022 R2 Morning Glory Bug Fix 1

src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/test/java/org/folio/rest/util/MockServer.java
Matching undefined and empty values works incorrectly in the tool CQL2PgJSON. We had to use workarounds. But now issue was solved. We can use more suitable cql match syntax after upgrading RMB in  the mod-finance-storage.
- Using correct matching syntax follow by [documentation](https://github.com/folio-org/raml-module-builder#cql-matching-undefined-or-empty-values)
[MODFIN-272](https://issues.folio.org/browse/MODFIN-272)
[RMB-932](https://issues.folio.org/browse/RMB-932)
- Do …
=> [MODFIN-272] Increase/decrease in allocation amounts for funds related to the same ledger are displayed in ledger Financial summary

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/ledger-rollover-logs.raml, src/main/java/org/folio/config/RestClientsConfiguration.java, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/LedgerRolloverLogsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/ledger/LedgerRolloverLogsService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/LedgerRolloverLogsApiTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/java/org/folio/services/ledger/LedgerRolloverLogsServiceTest.java
Provide new endpoint to retrieve result of rollover.
- Retrieved data from storage.
[MODFIN-270](https://issues.folio.org/browse/MODFIN-270) …
=> [MODFIN-270] Define and implement Business API : Ledger Rollover Logs

descriptors/ModuleDescriptor-template.json, ramls/ledger-rollover-budgets.raml, src/main/java/org/folio/config/RestClientsConfiguration.java, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/LedgerRolloverBudgetsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/ledger/LedgerRolloverBudgetsService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/LedgerRolloverBudgetsApiTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/java/org/folio/services/ledger/LedgerRolloverBudgetsServiceTest.java
To retrieve calculated budgets of preview rollover.
- Implemented ledger rollover budgets endpoint
[MODFIN-256](https://issues.folio.org/browse/MODFIN-256)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
=> [MODFIN-256] Define and implement Business API : Ledger Rollover Budgets

NEWS.md, pom.xml
=> [MODFIN-285] - Release 4.6.0

NEWS.md, src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java
=> [MODFIN-287] - Module release Morning Glory R2 2022 Hot Fix #1

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-241 …
=> [MODFIN-241]-added permission

src/main/java/org/folio/rest/impl/FiscalYearsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java, src/test/java/org/folio/rest/util/TestEntities.java, src/test/resources/mockdata/fiscal-years/fiscal_years_invalidCode.json
https://issues.folio.org/browse/MODFIN-291 …
=> [MODFIN-291]-added manual validation for fiscalyearcode format.

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/FiscalYearsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java, src/test/resources/mockdata/fiscal-years/fiscal_years_invalidCode.json
=> [MODFIN-292] - Release: 4.6.2

PULL_REQUEST_TEMPLATE.md, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODFIN-286
The property file and all logging commands have been adjusted.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> [MODFIN-286] - Logging improvement - Configuration

src/main/java/org/folio/rest/util/ErrorCodes.java
https://issues.folio.org/browse/UIF-429
Introduced budgetNotFoundForTransaction error Code instead of using genericError
Communication is paramount if that is to be …
=> [UIF-429] - Introducing error code for scenario

src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/java/org/folio/services/ledger/LedgerTotalsServiceTest.java
[MODFIN-299](https://issues.folio.org/browse/MODFIN-299) - Group and Ledger summary for Net Transfers do not include Rollover transfer amounts.
- Included rollover transfers in "net transfers" for group and ledger summaries.
- Updated unit tests.
See also: [integration test](https://github.com/folio-org/folio-integration-tests/pull/850).
- Did you modify …
=> [MODFIN-299] Include rollover transfers in summaries

NEWS.md, pom.xml
=> [MODFIN-305] - Release v4.7.0

NEWS.md, pom.xml, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/rest/impl/GroupFiscalYearSummariesTest.java
=> [MODFIN-310] - Release v4.7.1

descriptors/ModuleDescriptor-template.json, ramls/ledger-rollover-errors.raml, src/main/java/org/folio/rest/impl/LedgerRolloversErrorsApi.java, src/main/java/org/folio/services/ledger/LedgerRolloverErrorsService.java, src/test/java/org/folio/rest/impl/LedgerRolloverErrorsApiTest.java, src/test/java/org/folio/services/ledger/LedgerRolloverErrorsServiceTest.java
[MODFIN-316](https://issues.folio.org/browse/MODFIN-316) - Provide proxy endpoints to add and delete ledger rollover error in the business layer
- Added the new endpoints
- Updated the unit tests
This PR should be reviewed and merged together with PRs in [mod-orders](https://github.com/folio-org/mod-orders/pull/741) and [folio-integration-tests](https://github.com/folio-org/folio-integration-tests/pull/922).
- Are the JIRAs under …
=> [MODFIN-316] New proxy endpoints for ledger rollover errors

src/main/java/org/folio/rest/util/HelperUtils.java
=> [MODFISTO-405] - error response processing

ramls/funds.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/FundsApi.java, src/main/java/org/folio/services/fund/FundDetailsService.java, src/test/java/org/folio/services/fund/FundDetailsServiceTest.java
[MODFIN-317](https://issues.folio.org/browse/MODFIN-317)
Add possibility to filter expense classes by fiscal year id
fiscalYearId parameter was added to GET /finance/funds/$fundId/expense-classes endpoint. Expense classes are searched for fiscalYearId if passed or for current fiscal year if it's not set.
- Did you modify code to call some additional …
=> MODFIN-317 Add possibility to filter expense classes by fiscal year id

Dockerfile, Jenkinsfile, pom.xml
https://issues.folio.org/browse/MODFIN-322
updated to java 17
especially as the number of inter-module and …
=> [MODFIN-322]-Update to Java 17

descriptors/ModuleDescriptor-template.json, ramls/transaction.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/core/RestClient.java, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/transactions/BatchTransactionService.java, src/test/java/org/folio/rest/impl/TransactionApiTest.java, src/test/java/org/folio/rest/util/MockServer.java, src/test/resources/mockdata/transactions/batch_with_patch.json
[MODFIN-320](https://issues.folio.org/browse/MODFIN-320) - Create batch endpoint to update list of transactions at single request
Added the new endpoint. Implementation simply sends the request to mod-finance-storage without any additional check.
See also: [PR with new model in acq-models](https://github.com/folio-org/acq-models/pull/444), [mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/386).
- Are …
=> [MODFIN-320] New batch transaction processing endpoint processed in mod-finance-storage

ramls/transaction.raml, src/main/java/org/folio/rest/impl/TransactionsApi.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java
[MODFIN-320](https://issues.folio.org/browse/MODFIN-320) - Create batch endpoint to update list of transactions at single request
Fixed the endpoint to match the ticket goals.
to avoid breaking the folio-testing …
=> [MODFIN-320] Fixed batch endpoint

ramls/calculate-exchange.raml, src/main/java/org/folio/rest/helper/ExchangeHelper.java, src/main/java/org/folio/rest/helper/ExchangeRateHelper.java, src/main/java/org/folio/rest/impl/CalculateExchangeApi.java, src/main/java/org/folio/rest/impl/ExchangeRateApi.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/CalculateExchangeApiTest.java
https://issues.folio.org/browse/MODFIN-349
especially as the number of inter-module and inter-team dependencies …
=> [MODFIN-349] - Implement a new endpoint for currency exchange calculation

ramls/exchange.raml, src/main/java/org/folio/rest/helper/ExchangeHelper.java, src/main/java/org/folio/rest/impl/ExchangeApi.java, src/test/java/org/folio/rest/impl/ExchangeTest.java
https://issues.folio.org/browse/MODFIN-349
Added ability to add custom field
especially as the number of …
=> [MODFIN-349] -Added optional field to set custom exchange rate

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-349
especially as the number of inter-module and inter-team dependencies …
=> [MODFIN-349] - Added api to module descriptor

ramls/release-encumbrance.raml, ramls/transaction.raml, ramls/unrelease-encumbrance.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/EncumbranceApi.java, src/main/java/org/folio/services/transactions/BatchTransactionService.java, src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/test/java/org/folio/rest/impl/EncumbrancesTest.java, src/test/java/org/folio/rest/util/MockServer.java
[MODFIN-350](https://issues.folio.org/browse/MODFIN-350) - Use the batch API for the release/unrelease encumbrance endpoints
See ticket.
Communication is paramount if …
=> [MODFIN-350] Release/unrelease with new batch API

src/main/java/org/folio/rest/core/RestClient.java, src/main/java/org/folio/rest/core/models/RequestEntry.java, src/main/java/org/folio/rest/helper/AbstractHelper.java, src/main/java/org/folio/rest/helper/ExchangeHelper.java, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/impl/BaseApi.java, src/main/java/org/folio/services/budget/BudgetExpenseClassService.java, src/main/java/org/folio/services/budget/BudgetExpenseClassTotalsService.java, src/main/java/org/folio/services/budget/BudgetService.java, src/main/java/org/folio/services/budget/CreateBudgetService.java, src/main/java/org/folio/services/budget/RecalculatedBudgetBuilder.java, src/main/java/org/folio/services/configuration/ConfigurationEntriesService.java, src/main/java/org/folio/services/fiscalyear/FiscalYearService.java, src/main/java/org/folio/services/fund/FundDetailsService.java, src/main/java/org/folio/services/fund/FundService.java, src/main/java/org/folio/services/group/GroupExpenseClassTotalsService.java, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerDetailsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/main/java/org/folio/services/protection/AcqUnitMembershipsService.java, src/main/java/org/folio/services/protection/AcqUnitsService.java, src/main/java/org/folio/services/protection/ProtectionService.java, src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/main/java/org/folio/services/transactions/CreditService.java, src/main/java/org/folio/services/transactions/EncumbranceService.java, src/main/java/org/folio/services/transactions/PaymentService.java, src/main/java/org/folio/services/transactions/TransactionRestrictService.java
https://issues.folio.org/browse/MODFIN-232
especially as the number of inter-module and inter-team dependencies …
=> [MODFIN - 232] - Loggin improvement

descriptors/ModuleDescriptor-template.json
[MODFIN-350](https://issues.folio.org/browse/MODFIN-350) - Use the batch API for the release/unrelease encumbrance endpoints
Fixed permissions for release/unrelease endpoints.
to avoid breaking the folio-testing …
=> [MODFIN-350] Fixed permissions

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODFIN-357
=> MODFIN-357. Fixed missed declaration of backend permissions

NEWS.md, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/rest/impl/GroupFiscalYearSummariesTest.java
=> [MODFIN-355] - Release v4.8.1

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODFIN-363
=> MODFIN-363. Missing ledger-rollover interface dependency in module descriptor

pom.xml, src/test/java/org/folio/services/budget/BudgetExpenseClassServiceTest.java, src/test/java/org/folio/services/fund/FundCodeExpenseClassesServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-362
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
=> [MODFIN-362] Upgrade RAML Module Builder

pom.xml
Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md
=> MODFIN-362. Upgrade folio-di-support

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODFIN-366
=> MODFIN-366. Quesnelia module release

descriptors/ModuleDescriptor-template.json
[MODFIN-352](https://folio-org.atlassian.net/browse/MODFIN-352) - Remove the old transaction API
Added missing permission.
[Original PR](https://github.com/folio-org/mod-finance/pull/245)
to avoid breaking the …
=> [MODFIN-352] Added missing permission

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/util/ResourcePathResolver.java
[MODFISTO-460](https://folio-org.atlassian.net/browse/MODFISTO-460) - Remove the old transaction API (storage)
- Updated the storage transaction API version
- Removed unused endpoints
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/408)
Ideally, all the PRs involved in …
=> [MODFISTO-460] Updated finance storage transaction  API version

descriptors/ModuleDescriptor-template.json
=> MODFIN-352 fix permissions

src/main/java/org/folio/services/budget/BudgetExpenseClassTotalsService.java, src/test/java/org/folio/services/budget/BudgetExpenseClassTotalsServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-372
updated totalExpended calculation
Change the calculation: replace:
percentageExpended = expended / (budget.expended+ budget.overExpened) * 100
by:
percentageExpended = expended / budget.expended * 100
Ideally, all the PRs involved in breaking changes …
=> [MODFIN-372] - updated expendedPercentage calculation

src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/rest/impl/GroupFiscalYearSummariesTest.java, src/test/java/org/folio/services/ledger/LedgerTotalsServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-373
=> [MODFIN-373] - Wrong overEncumbrance for ledgers and fiscal years

src/main/java/org/folio/services/budget/BudgetService.java, src/test/java/org/folio/services/budget/BudgetServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-374
Make validation the same as in mod-finance-storage BatchTransactionsChecks:
- https://github.com/folio-org/mod-finance-storage/blob/master/src/main/java/org/folio/service/transactions/batch/BatchTransactionChecks.java#L215
- https://github.com/folio-org/mod-finance-storage/blob/master/src/main/java/org/folio/service/transactions/batch/BatchTransactionChecks.java#L248
=> [MODFIN-374]. Update budget validation when updating a budget

descriptors/ModuleDescriptor-template.json
=> MODFIN-377 clean up permissions

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102
especially as the number of inter-module and inter-team …
=> [FOLIO-4102] - Release v5.0.0

src/main/java/org/folio/rest/util/BudgetUtils.java, src/main/java/org/folio/services/budget/RecalculatedBudgetBuilder.java, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/services/budget/RecalculateBudgetServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-394
=> [MODFIN-394]. Budget summary for Net Transfers do not include Rollover transfer amounts.

NEWS.md, pom.xml, src/main/java/org/folio/rest/util/BudgetUtils.java, src/main/java/org/folio/services/budget/RecalculatedBudgetBuilder.java, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/services/budget/RecalculateBudgetServiceTest.java
Prepare for Ramsons Bug Fix release that include ticket https://folio-org.atlassian.net/browse/MODFIN-394
=> Release Ramsons Bug Fix 5.0.1

NEWS.md, pom.xml, src/main/java/org/folio/rest/util/BudgetUtils.java, src/main/java/org/folio/services/budget/RecalculatedBudgetBuilder.java, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/services/budget/RecalculateBudgetServiceTest.java
Make Hot fix relasing for Quesnelia that includes this ticket:
* [MODFIN-394]. Budget summary for Net Transfers do not include Rollover transfer amounts.
=> [MODFIN-394]. Budget summary for Net Transfers do not include Rollover transfer amounts

src/main/java/org/folio/services/fiscalyear/FiscalYearApiService.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java
https://folio-org.atlassian.net/browse/MODFIN-386
- removed updating currency with system currency
especially as the …
=> [MODFIN-386] - Editing fiscal year at any time changes currency based on current system currency

src/main/java/org/folio/services/financedata/FinanceDataService.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java
[MODFIN-402](https://folio-org.atlassian.net/browse/MODFIN-402) - Update current budget value and display budget records in appropriate fiscal year in downloaded .csv allocations
- Added `budgetCurrentAllocation`
- Added support for updating the fund status
- Only check for budget properties if a budget id is specified (see [MODFIN-406](https://folio-org.atlassian.net/browse/MODFIN-406))
Related PRs: [mod-finance-storage](https://github.com/folio-org/mod-finance-storage/pull/448), [integration test
](https://github.com/folio-org/folio-integration-tests/pull/1690)
If there are breaking changes, …
=> [MODFIN-402] Fixes to finance data endpoint

src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java
[MODFIN-407](https://folio-org.atlassian.net/browse/MODFIN-407) - Make fund active when creating or increasing allocation
- Moved allocation creation to mod-finance-storage
- Updated tests
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/449), [integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1698)
- Do PRs exist for these …
=> [MODFIN-407] Finance data: moved allocation creation to mod-finance-storage

src/main/java/org/folio/rest/util/HelperUtils.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-403
- Improved HttpException creation
- Removed not required validations
Communication is paramount if that is to be …
=> [MODFIN-403] - Improve Bulk Fund Updates validation Part 1

src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java, src/test/java/org/folio/services/financedata/FinanceDataValidatorTest.java
[MODFIN-403](https://folio-org.atlassian.net/browse/MODFIN-403)
- Delete validation for required fields for transactionDescription and transactionTags because it is optional fields [Link ](https://github.com/folio-org/mod-finance/blob/master/src/main/java/org/folio/services/financedata/FinanceDataService.java#L225)
- Add appropriate error code Budget status entered into the spreadsheet does not match any valid status in FOLIO
- Add validation when Budget UUID does not exist in the system and does not match with appropriate Fund
- Add validation when Fund UUID does not exist in the system and does not match with appropriate Ledger or Group
- Add validation for duplicated rows in the spreadsheet(fiscalYearId, budgetId, fundId)
- allocationChange should not be a required field.
Before …
=> [MODFIN-403] - Improve Bulk Fund Updates validation part 2

src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/test/java/org/folio/services/financedata/FinanceDataValidatorTest.java
- improved isChanged checks
- refactored fund tags comparision
especially as the number of inter-module and …
=> [MODFIN-403] - Improve isFundChanged check

descriptors/ModuleDescriptor-template.json, ramls/fund-update-log.raml, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/main/java/org/folio/services/fund/FundUpdateLogService.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java, src/test/java/org/folio/services/financedata/FinanceDataValidatorTest.java
https://folio-org.atlassian.net/browse/MODFIN-415
especially as the number of inter-module and inter-team …
=> [MODFIN-415] - Add job number retrieval and enhance finance data validation

src/main/java/org/folio/rest/core/RestClient.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java, src/test/java/org/folio/services/financedata/FinanceDataValidatorTest.java
- https://folio-org.atlassian.net/browse/MODFIN-419
especially as the number of inter-module and inter-team …
=> [MODFIN-419] - Display updated values on job details log screen

src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-415
- process worksheetName
- improve validation
especially as the …
=> [MODFIN-416] - Enhance finance data jobName processing and validation logic

src/main/java/org/folio/rest/impl/ExchangeApi.java, src/main/java/org/folio/services/exchange/ExchangeService.java, src/test/java/org/folio/services/exchange/ExchangeServiceTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-410>
- Remove unnecessary argument Context, which can be retrieved from RequestContext
=> [MODFIN-410-2]. Simplify exchange rate method args

NEWS.md, pom.xml, src/main/java/org/folio/services/protection/AcqUnitConstants.java, src/main/java/org/folio/services/protection/AcqUnitsService.java, src/test/java/org/folio/rest/impl/FinanceDataApiTest.java, src/test/java/org/folio/services/protection/AcqUnitsServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-421
especially as the number of inter-module and inter-team …
=> Bug Fix Release v5.1.1

.github/dependabot.yml, CODEOWNERS, PULL_REQUEST_TEMPLATE.md
https://folio-org.atlassian.net/browse/MODFIN-435
- Setup dependant bot
- Add codeowners
- Simplify PR_TEMPLATE
=> MODFIN-435. Setup dependabot for your module

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/exchange-batch.raml, src/main/java/org/folio/rest/impl/ExchangeApi.java, src/main/java/org/folio/rest/util/CacheUtils.java, src/main/java/org/folio/services/exchange/CustomJsonExchangeRateProvider.java, src/main/java/org/folio/services/exchange/ExchangeService.java, src/test/java/org/folio/rest/impl/ExchangeTest.java, src/test/java/org/folio/services/exchange/ExchangeServiceTest.java, src/test/java/org/folio/util/CopilotGenerated.java
[[MODFIN-423] Provide batch endpoint to get exchange rates](https://folio-org.atlassian.net/browse/MODFIN-423)
Add Exchange Batch API and exchange rate calculations schema
=> [MODFIN-423] Provide batch endpoint to get exchange rates

descriptors/ModuleDescriptor-template.json, ramls/ledgers.raml, src/main/java/org/folio/rest/impl/LedgersApi.java, src/test/java/org/folio/rest/impl/FiscalYearTest.java
https://folio-org.atlassian.net/browse/MODORDERS-1254
Expose get planned fiscal year endpoint that will be using by feature from mod-orders to show planned fiscal years for order
---
=> MODFIN-439. Add endpoint to provide planned fiscal year
