folio-org/mod-finance

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
=> MODFIN-95 FOLIO-2358 manage container memory

ramls/group-fiscal-year-summaries.raml, src/main/java/org/folio/rest/helper/GroupFiscalYearSummariesHelper.java, src/main/java/org/folio/rest/impl/GroupFiscalYearSummariesApi.java
[MODFIN-102](https://issues.folio.org/browse/MODFIN-102) - GET /finance/group-fiscal-year-summaries pagination bug
Pagination was removed.
Pagination was removed, GroupFundFiscalYears limit = Integer.MAX_VALUE. …
=> MODFIN-102 - GET /finance/group-fiscal-year-summaries pagination bug

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/rest/helper/TransactionRestrictHelper.java, src/main/java/org/folio/rest/helper/TransactionsHelper.java, src/main/java/org/folio/rest/impl/FundsApi.java, src/main/java/org/folio/rest/util/ErrorCodes.java, src/test/java/org/folio/rest/impl/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/TransactionTest.java, src/test/resources/mockdata/funds/ASIAHIST.json, src/test/resources/mockdata/funds/CANHIST.json, src/test/resources/mockdata/funds/HIST.json, src/test/resources/mockdata/funds/LATHIST.json, src/test/resources/mockdata/transactions/allocations.json, src/test/resources/mockdata/transactions/transfers.json
[MODFIN-110](https://issues.folio.org/browse/MODFIN-110) - Enforce allocatedFromIds and allocatedToIds
Allocations and transfers to/from budgets from another budget should be restricted by the fund.allocatedToIds and fund.allocatedFromIds fields in the funds associated with the budgets involved.
* Transfers/allocations between budgets are restricted according to requirements
* Unit tests are updated
- Are the JIRAs under active …
=> MODFIN-110 - Enforce allocatedFromIds and allocatedToIds

src/main/java/org/folio/services/BudgetService.java, src/test/java/org/folio/services/BudgetServiceTest.java
https://issues.folio.org/browse/MODFIN-147 check remaining encumbrance and expenditure after merging budgets from request and storage …
=> MODFIN-147 Budget allocation calculation out of sync with transaction log

src/main/java/org/folio/rest/exception/HttpException.java, src/main/java/org/folio/rest/util/ErrorCodes.java
[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
Return the "conflict" error code when a 409 is returned by storage with no XML errors in the response body.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> [MODFISTO-303] Added the conflict error code

src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/test/java/org/folio/rest/util/MockServer.java
When there are more than five funds in one group and move alocation is between that group, an error may occur because the request to retrieving transactions from mod-finance-storage is sent in chunks.
- Moved the logic to identify allocation in one group and ledger from CQL query to code.
[MODFIN-274](https://issues.folio.org/browse/MODFIN-274)
Ideally …
=> [MODFIN-274] Incorrect calculation of allocationTo and allocationFrom in case of more than 5 funds exist in ledger or group

pom.xml
There is a lot of failures in karate tests today,
In logs in karate report I see occurences of this error: 
`status code was: 500, expected: 201, response time in milliseconds: 282, url: https://folio-testing-karate-okapi.ci.folio.org/orders/order-lines, response: 
{
"errors" : [ {
"message" : "Generic error",
"code" : "genericError",
"parameters" : [ ],
"cause" : "Unrecognized field \"recordsSource\" (class org.folio.rest.jaxrs.model.Config), not marked as ignorable (10 known properties: \"default\", \"userId\", \"id\", \"module\", \"configName\", \"metadata\", \"enabled\", \"code\", \"description\", \"value\"])\n at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.folio.rest.jaxrs.model.Configs[\"configs\"]->java.util.ArrayList[0]->org.folio.rest.jaxrs.model.Config[ …
=> Increase version of mod-configuration client in order to fix karate tests

src/main/java/org/folio/rest/helper/FundsHelper.java, src/main/java/org/folio/services/budget/BudgetExpenseClassService.java, src/main/java/org/folio/services/budget/BudgetService.java, src/test/java/org/folio/rest/impl/FundsApiTest.java, src/test/resources/mockdata/funds/funds.json
[MODFIN-264](https://issues.folio.org/browse/MODFIN-264) - Optimistic locking ignored when changing expense class and adding group
- Switched order of operations for budget and fund updates
- Implemented a rollback in case expense class or group updates fail
- Creating new expense class first, as it is more likely to fail than update and delete
- Updated unit tests
See [integration test](https://github.com/folio-org/folio-integration-tests/pull/842).
It's tricky to implement an async operation within an error handling block. I had to return a future in `handle()` and evaluate it afterwards with `.thenCompose(Function.identity())`.
- Does …
=> [MODFIN-264] Rollback for budget and fund updates

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/budgets.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODFIN-307 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/rest/impl/GroupFiscalYearSummariesTest.java
[MODFIN-308](https://issues.folio.org/browse/MODFIN-308) - Maintain displaying "Available" as a negative number for group and ledger
- Made changes suggested in the JIRA (removing `.max(BigDecimal.ZERO)` when calculating available for the summary)
- Updated unit tests
See related [integration test PR](https://github.com/folio-org/folio-integration-tests/pull/885).
- Do PRs exist for these …
=> [MODFIN-308] Keep available negative in summary

descriptors/ModuleDescriptor-template.json
The following interface is missing in "requires" section of module descriptor
{
"id": "finance-storage.budget-expense-classes",
"version": "2.0"
} 
https://issues.folio.org/browse/MODFIN-324
=> MODFIN-324. Add missing required interface to module descriptor

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODFIN-329
Permissions: finance.acquisitions-units-assignments.assign, finance.acquisitions-units-assignments.manage used in UI but not created in module descriptor.
In this PR we are declaring them in module descriptor and they will be automatically created
=> [MODFIN-329] Create necessary missed permissions

descriptors/ModuleDescriptor-template.json, ramls/budgets.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/impl/BudgetsApi.java, src/main/java/org/folio/services/budget/BudgetExpenseClassTotalsService.java, src/main/java/org/folio/services/budget/BudgetService.java, src/main/java/org/folio/services/budget/RecalculateBudgetService.java, src/main/java/org/folio/services/budget/RecalculatedBudgetBuilder.java, src/main/java/org/folio/services/group/GroupExpenseClassTotalsService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/BudgetsApiTest.java, src/test/java/org/folio/services/budget/BudgetServiceTest.java, src/test/java/org/folio/services/budget/RecalculateBudgetServiceTest.java, src/test/java/org/folio/services/ledger/LedgerDetailsServiceTest.java
=> [MODFIN-344] - Implementing the functionality to recalculate budgets based on conducted transactions.

descriptors/ModuleDescriptor-template.json, ramls/unrelease-encumbrance.raml, src/main/java/org/folio/rest/impl/EncumbranceApi.java, src/main/java/org/folio/services/transactions/CommonTransactionService.java, src/test/java/org/folio/rest/impl/EncumbrancesTest.java
https://issues.folio.org/browse/MODFIN-346
Endpoint will be implemented
Unit tests were written
especially as the …
=> [MODFIN-346] - Implement unrelease encumbrance endpoint

descriptors/ModuleDescriptor-template.json
Recalculate Budget endpoint uses Get Budget expense classes permission instead of Get expense classes
=> MODFIN-344. Update module permissions

src/main/java/org/folio/rest/util/HelperUtils.java, src/main/java/org/folio/services/group/GroupFiscalYearTotalsService.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/test/java/org/folio/rest/impl/GroupFiscalYearSummariesTest.java
Group or Fiscal Year summaries show incrorrectly when fund has no initial allocation and allocation from other fund which is not part of group
- To identify initial allocation or increase allocation we can filter it out by attribute when fromFundId is null
Ideally, all the PRs involved in breaking …
=> [MODFIN-355] - Incorrectly calculated increase allocation for group financial summary

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/transactions/BatchTransactionService.java, src/test/java/org/folio/rest/impl/TransactionApiTest.java, src/test/resources/mockdata/transactions/batch_with_delete.json
[MODFISTO-432](https://folio-org.atlassian.net/browse/MODFISTO-432) - Implement logic to replace AllOrNothing to process list of transaction from request payload
Added a check to make sure encumbrances to delete are not connected to an invoice. This could not be added to mod-finance-storage because it would break the encumbrance script.
- Did you modify …
=> [MODFISTO-432] Add a check before deleting encumbrances

src/main/java/org/folio/services/transactions/BaseTransactionService.java, src/main/java/org/folio/services/transactions/BatchTransactionService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/services/transactions/BatchTransactionServiceTest.java
[MODORDERS-1043](https://folio-org.atlassian.net/browse/MODORDERS-1043) - Remove pending payment encumbrance links when encumbrances are deleted
Allow removing an encumbrance linked to an approved invoice if the pending payment link to the encumbrance is removed in the same batch.
See also: [mod-orders PR](https://github.com/folio-org/mod-orders/pull/853), [integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1278).
- Do JIRAs exist to update the …
=> [MODORDERS-1043] Allow removing encumbrance with pending payment if updated in same batch

pom.xml
[[MODFIN-380] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODFIN-380)
- Update versions
- Add module descriptor validator
=> [MODFIN-380] Update libraries of dependant acq modules to the latest versions

src/main/java/org/folio/rest/impl/FinanceDataApi.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/test/java/org/folio/rest/impl/FinanceDataApiTest.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java, src/test/resources/mockdata/finance-data/fy_finance_data_collection_put.json
[Add dry-run mode for bulk FY finance updates](https://folio-org.atlassian.net/browse/MODFIN-382)
- added new update type
- added calculation of after allocation
- updated service to skip commit to db section if update type is preview
=> [MODFIN-382] - Add dry-run mode for bulk FY finance updates

descriptors/ModuleDescriptor-template.json, ramls/transaction.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/models/LedgerFiscalYearTransactionsHolder.java, src/main/java/org/folio/models/TransactionTotalSetting.java, src/main/java/org/folio/rest/util/BudgetUtils.java, src/main/java/org/folio/rest/util/ResourcePathResolver.java, src/main/java/org/folio/services/ledger/LedgerTotalsService.java, src/main/java/org/folio/services/transactions/TransactionTotalService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/services/ledger/LedgerTotalsServiceTest.java, src/test/java/org/folio/services/transactions/TransactionTotalApiServiceTest.java, src/test/java/org/folio/services/transactions/TransactionTotalServiceTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-391>
- Create a new service which will fetch aggregated transaction totals from storage and use it in Ledger total calculation
- Update LedgerTotalsService to use new TransactionTotalService instead of TransactionService
=> [MODFIN-391]. Minimize amount of requests to retrieve transactions for ledger

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/services/budget/CreateBudgetService.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/group/GroupFundFiscalYearService.java, src/test/java/org/folio/services/budget/CreateBudgetServiceTest.java, src/test/java/org/folio/services/group/GroupFundFiscalYearServiceTest.java
[MODFISTO-517](https://folio-org.atlassian.net/browse/MODFISTO-517) - Create budget when adding batch allocation to fund without budget
- Prevent NPE when current allocation or change is null.
- When creating a budget, do not update group-fund-fiscal-year anymore, as this is now done in mod-finance-storage
- Updated permissions and tests
[mod-finance-storage PR](https://github.com/folio-org/mod-finance-storage/pull/450), [integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1704)
- What other modules …
=> [MODFISTO-517] Moved group-fund-fiscal-year update when creating a budget to mod-finance-storage

src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/services/financedata/FinanceDataService.java, src/main/java/org/folio/services/financedata/FinanceDataValidator.java, src/main/java/org/folio/services/fund/FundUpdateLogService.java, src/test/java/org/folio/ApiTestSuite.java, src/test/java/org/folio/rest/impl/EntitiesCrudBasicsTest.java, src/test/java/org/folio/rest/impl/FundUpdateLogApiTest.java, src/test/java/org/folio/services/financedata/FinanceDataServiceTest.java, src/test/java/org/folio/services/fund/FundUpdateLogServiceTest.java, src/test/resources/mockdata/fund-update-logs/fund-update-logs.json
- <https://folio-org.atlassian.net/browse/MODFIN-416>
- Populate `FundUpdateLog` with `ledgerId` and `acqUnitIds` to restrict log fetching by an ACQ Unit on the Ledger
- Add new unit tests and update existing integration tests
=> [MODFIN-416]. Batch allocation logs - restrict by acq units

src/main/java/org/folio/services/budget/CreateBudgetService.java, src/test/java/org/folio/services/budget/CreateBudgetServiceTest.java
[MODFIN-405](https://folio-org.atlassian.net/browse/MODFIN-405) - Current budget is created with incorrect values ​​despite the received error
When creating an inactive budget with an allocation:
- First create an active budget
- Then create the allocation
- Then make the budget inactive
When an inactive budget is created without an allocation, simply create the budget with the right status.
[Integration tests PR](https://github.com/folio-org/folio-integration-tests/pull/1736)
- …
=> [MODFIN-405] Support creating an inactive budget with an allocation

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/budget/CreateBudgetService.java, src/test/java/org/folio/services/budget/CreateBudgetServiceTest.java
[MODFIN-405](https://folio-org.atlassian.net/browse/MODFIN-405) - Current budget is created with incorrect values ​​despite the received error
- Handle negative budget allocation with a new error code.
- Added missing permission.
[Integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1747)
- Did you modify code to call some …
=> [MODFIN-405] Handle negative budget allocation

src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/services/exchange/CustomJsonExchangeRateProvider.java, src/main/java/org/folio/services/exchange/handler/TreasuryGovCustomJsonHandler.java, src/test/java/org/folio/services/exchange/ExchangeServiceTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-410>
- Replace IllegalStateException with an enhanced HttpException
- Add return 1 if from and to currencies are the same (mimic Java Money Moneta's IDENTITY provider's response)
> Forward conversion: https://github.com/JavaMoney/jsr354-ri/blob/4cab8838260af222fa2d2b1cd2512bc1ae7ee1a9/moneta-convert/moneta-convert-base/src/main/java/org/javamoney/moneta/convert/internal/IdentityRateProvider.java#L70
> Reverse conversion: https://github.com/JavaMoney/jsr354-ri/blob/4cab8838260af222fa2d2b1cd2512bc1ae7ee1a9/moneta-convert/moneta-convert-base/src/main/java/org/javamoney/moneta/convert/internal/IdentityRateProvider.java#L87
=> [MODFIN-410-3]. Enhance TreasuryGovCustomJsonHandler exception handling

src/main/java/org/folio/models/ExpenseClassUnassigned.java, src/main/java/org/folio/rest/impl/BudgetsApi.java, src/main/java/org/folio/rest/impl/GroupsApi.java, src/main/java/org/folio/services/budget/BudgetExpenseClassTotalsService.java, src/main/java/org/folio/services/group/GroupExpenseClassTotalsService.java, src/test/java/org/folio/services/ExpenseClassServiceTest.java, src/test/java/org/folio/services/budget/BudgetExpenseClassTotalsServiceTest.java, src/test/java/org/folio/services/group/GroupExpenseClassTotalsServiceTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-433>
- Update Budget and Group services with new code that will convert transactions without expense classes into a separate group
- This new group will have an id of UNASSIGNED and name of Unassigned, and it will help display the previously hidden totals
- Clean and refactor API and Service classes
- Update unit tests
> A fund without any expense classes
> A fund with expense classes
> A group with both of the funds shown above
=> [MODFIN-433]. Include totals without expense class for expense-classes-totals

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/services/ledger/LedgerRolloverBudgetsService.java, src/test/java/org/folio/services/ledger/LedgerRolloverBudgetsServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-439
Apply rounding before returning response
---
=> MODFIN-439. Rounding to too many decimals when rolling over budgets and increasing by percentage
